version: '3.6'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    command: [ "mongod", "--replSet", "analytics", "--bind_ip_all" ]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u root -p password --quiet) -eq 1
      interval: 10s
      start_period: 10s

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    image: node
    ports:
      - 3000:3000
    environment:
      JWT_SECRET: ImAstrongSecret
      URL_MONGO: mongodb+srv://stervinoug36:quxjELIaHIRwMBhd@cluster0.jru3gyx.mongodb.net/?retryWrites=true&w=majority
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: npm run dev

volumes:
  db-data: {}
  pg-data: {}
