export const siteKey = Symbol('site')
export const sitesKey = Symbol('sites')
export const errorsKey = Symbol('errors')
export const createSiteKey = Symbol('createSite')
export const refreshApiKeyKey = Symbol('refreshApiKey')
