export const untrackedPagesKey = Symbol('untrackedPages')
export const untrackedPageKey = Symbol('untrackedPage')
export const errorsKey = Symbol('errors')
export const createUntrackedPageKey = Symbol('createUntrackedPage')
export const updateUntrackedPageKey = Symbol('updateUntrackedPage')
export const deleteUntrackedPageKey = Symbol('deleteUntrackedPage')
